const joinTraits = (traits = []) => traits.filter(Boolean).join(", ");

function buildPersona(c) {
  return [
    `Name: ${c.name || "Unknown"}`,
    c.nickname ? `Nickname: ${c.nickname}` : "",
    c.age ? `Age: ${c.age}` : "",
    c.gender ? `Gender: ${c.gender}` : "",
    c.species ? `Species: ${c.species}` : "",
    c.traits?.length ? `Traits: ${joinTraits(c.traits)}` : "",
    c.description ? `Appearance: ${c.description}` : "",
    c.background ? `Lore: ${c.background}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

export function toSillyTavernV1(c) {
  return {
    name: c.name || "Unnamed",
    description: buildPersona(c),
    personality: joinTraits(c.traits),
    scenario: c.scenario || "",
    first_mes: c.greeting || "",
    mes_example: c.exampleDialogue || "",
    avatar: c.avatarData || c.avatarUrl || "",
  };
}

export function toSillyTavernV2(c) {
  const data = {
    name: c.name || "Unnamed",
    description: buildPersona(c),
    personality: joinTraits(c.traits),
    scenario: c.scenario || "",
    first_mes: c.greeting || "",
    mes_example: c.exampleDialogue || "",
    creator_notes: "Generated by Character Designer",
    tags: c.traits || [],
    extensions: {
      talkativeness: 0.5,
      depth_prompt: "",
      world: "",
    },
  };

  return {
    spec: "chara_card_v2",
    spec_version: "2.0",
    data,
  };
}
